### ISSUE TITLE
Cannot scroll in Files section

### ISSUE THREAD

**Issue by victordiaz** [victordiaz/PHONK-editor#15]
As mentioned in [https://github.com/victordiaz/PHONK/issues/32](https://github.com/victordiaz/PHONK/issues/32)

Files cannot be scrolled

**Comment by SuperUserNameMan** [comment]
![webeditor_files_box_doesnot_scroll](https://user-images.githubusercontent.com/9801802/86512306-49c34480-be01-11ea-8377-0c7f12e2930c.png)
